class Headers:
    def oauth(self, token):
        '''
        Create a header included in each requests sending with this tools.
        Specify a Content-Type and Authorizations necessary for Dazzl API.

        @param token: String generated by backend service

        >>> Headers().oauth('SuperToken')
        {'Content-Type': 'application/json', 'Authorizations': 'Bearer SuperToken'}

        '''
        return {
            'Content-Type': 'application/json',
            'Authorizations': 'Bearer '+token
        }


if __name__ == "__main__":
    import doctest
    doctest.testmod()
